from __future__ import annotations

# This engine is contract-agnostic: `service`, `domain` and the per-doc
# `section` are read from the repo's `docs/.docs-manifest.yaml`, never
# hardcoded here. See `_manifest.GenContext`.

# Note: tree generators source files from `git ls-files`, not a filesystem
# walk, so an explicit prune list is no longer required — anything not
# tracked by git is invisible by construction. See `_gen_docs/_git.py`.

GENERATED_NOTE = (
    "<!-- GENERATED by gen_docs — do not hand-edit. "
    "Re-run the generator instead. -->"
)
