from __future__ import annotations

import sys
from pathlib import Path

from .._manifest import (
    MANIFEST_REL,
    _git_head,
    _install_literal_str_representer,
    _yaml_module,
)


def gen_bootstrap(
    repo: Path,
    contract: Path,
    service: str | None = None,
    force: bool = False,
) -> int:
    """Create `docs/.docs-manifest.yaml` from a caller-supplied contract.

    No contract template is bundled in this engine — the path to one is
    passed in (e.g. by the /init-docs flow). Returns an exit code.
    """
    yaml = _yaml_module()
    _install_literal_str_representer(yaml)

    if not contract.exists():
        print(f"error: contract template not found at {contract}", file=sys.stderr)
        return 2

    dest = repo / MANIFEST_REL
    if dest.exists() and not force:
        print(f"error: {MANIFEST_REL} already exists. Use --force to overwrite, "
              "or run `migrate` to reconcile against the current contract.",
              file=sys.stderr)
        return 1

    with contract.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    head = _git_head(repo)
    if head is None:
        print("warning: could not resolve HEAD; commits will be null. "
              "Initialize git or commit first.", file=sys.stderr)

    # `service` comes from the caller, else from the contract, else a neutral
    # placeholder — never a hardcoded backend default.
    data["service"] = service or data.get("service") or "service"
    data["bootstrap_commit"] = head

    needs_adapt: list[str] = []
    for entry in data.get("docs") or []:
        entry["acknowledged_at_commit"] = head
        trig = entry.get("triggers") or {}
        produces = entry.get("produces") or {}
        if trig.get("paths") is None:
            needs_adapt.append(f"{entry['path']} (triggers.paths)")
        if produces.get("type") == "script" \
                and produces.get("params") is None \
                and (produces.get("params_needed") or {}):
            needs_adapt.append(f"{entry['path']} (produces.params)")

    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("w", encoding="utf-8") as fh:
        fh.write(
            "# docs/.docs-manifest.yaml — local source of truth for this\n"
            "# repo's /docs. Generated by `gen_docs bootstrap` from a contract\n"
            "# template. Run `gen_docs adapt` (or its agent equivalent) to fill\n"
            "# `triggers.paths` and `produces.params` for this repo.\n\n"
        )
        yaml.dump(
            data, fh,
            sort_keys=False, default_flow_style=False,
            allow_unicode=True, width=100,
        )

    print(f"  wrote {MANIFEST_REL}")
    print(f"  bootstrap_commit: {head or '(none)'}")
    if needs_adapt:
        print(f"  {len(needs_adapt)} project-specific field(s) await `adapt`:")
        for line in needs_adapt[:8]:
            print(f"    - {line}")
        if len(needs_adapt) > 8:
            print(f"    … and {len(needs_adapt) - 8} more")
    return 0
